---
- name: Execute LAMP Stack Deployment Script
  hosts: slave
  become: yes
  tasks:
    - name: Transfer Deployment Script to Slave Node
      copy: src=deploy.sh dest=/tmp/deploy.sh mode=0755

    - name: Execute Deployment Script
      shell: /tmp/deploy.sh
